-- MySQL Script generated by MySQL Workbench
-- Sun Nov  6 17:25:11 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Libros
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Libros
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Libros` DEFAULT CHARACTER SET utf8 ;
USE `Libros` ;

-- -----------------------------------------------------
-- Table `Libros`.`tblUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Libros`.`tblUsuario` (
  `strCedulaUsuario` VARCHAR(20) NOT NULL,
  `StrPrimerNombre` VARCHAR(45) NOT NULL,
  `strSegundoNombre` VARCHAR(45) NULL,
  `strPrimerApellido` VARCHAR(45) NOT NULL,
  `strSegundoApellido` VARCHAR(45) NOT NULL,
  `strCorreo` VARCHAR(45) NOT NULL,
  `strContrasena` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`strCedulaUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Libros`.`tblGenero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Libros`.`tblGenero` (
  `intIdGenero` INT NOT NULL AUTO_INCREMENT,
  `strNombreGenero` VARCHAR(25) NOT NULL,
  `strDescripcionGenero` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`intIdGenero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Libros`.`tblLibros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Libros`.`tblLibros` (
  `IntIdLibro` INT NOT NULL AUTO_INCREMENT,
  `strNombre` VARCHAR(45) NOT NULL,
  `strDescripcion` VARCHAR(45) NOT NULL,
  `strAutor` VARCHAR(45) NOT NULL,
  `intAnoCreacion` INT NOT NULL,
  `tblGenero_intIdGenero` INT NOT NULL,
  PRIMARY KEY (`IntIdLibro`, `tblGenero_intIdGenero`),
  CONSTRAINT `fk_tblLibros_tblGenero1`
    FOREIGN KEY (`tblGenero_intIdGenero`)
    REFERENCES `Libros`.`tblGenero` (`intIdGenero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Libros`.`tblEmpleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Libros`.`tblEmpleado` (
  `strCedulaEmpleado` VARCHAR(20) NOT NULL,
  `strNombreEmpleado` VARCHAR(45) NOT NULL,
  `strApellidoEmpleado` VARCHAR(45) NOT NULL,
  `strCorreoEmpleado` VARCHAR(45) NOT NULL,
  `strContrasenaEmpleado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`strCedulaEmpleado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Libros`.`tblPrestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Libros`.`tblPrestamo` (
  `intIdPrestamo` INT NOT NULL AUTO_INCREMENT,
  `tblUsuario_strCedulaUsuario` VARCHAR(20) NOT NULL,
  `tblEmpleado_strCedulaEmpleado` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`intIdPrestamo`, `tblUsuario_strCedulaUsuario`, `tblEmpleado_strCedulaEmpleado`),
  CONSTRAINT `fk_tblPrestamo_tblUsuario1`
    FOREIGN KEY (`tblUsuario_strCedulaUsuario`)
    REFERENCES `Libros`.`tblUsuario` (`strCedulaUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tblPrestamo_tblEmpleado1`
    FOREIGN KEY (`tblEmpleado_strCedulaEmpleado`)
    REFERENCES `Libros`.`tblEmpleado` (`strCedulaEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Libros`.`tblDetallePrestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Libros`.`tblDetallePrestamo` (
  `tblPrestamo_intIdPrestamo` INT NOT NULL,
  `tblLibros_IntIdLibro` INT NOT NULL,
  `dateFechaPrestamo` DATE NOT NULL,
  `boolEstado` TINYINT NOT NULL,
  PRIMARY KEY (`tblPrestamo_intIdPrestamo`, `tblLibros_IntIdLibro`),
  CONSTRAINT `fk_tblPrestamo_has_tblLibros_tblPrestamo1`
    FOREIGN KEY (`tblPrestamo_intIdPrestamo`)
    REFERENCES `Libros`.`tblPrestamo` (`intIdPrestamo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tblPrestamo_has_tblLibros_tblLibros1`
    FOREIGN KEY (`tblLibros_IntIdLibro`)
    REFERENCES `Libros`.`tblLibros` (`IntIdLibro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
